version: 2.1

jobs:
  deployment:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - run:
          name: Push to PyPI
          command: |
            poetry publish --build --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" --no-interaction

workflows:
  deployment-workflow:
    jobs:
      - deployment:
          context:
            - pypi
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
